//
//  Constants.swift
//  BluetoothHRM
//
//  Created by Ethan Hess on 5/12/16.
//  Copyright © 2016 Ethan Hess. All rights reserved.
//

import Foundation

let POLARH7_HRM_DEVICE_INFO_SERVICE_UUID = "180A"
let POLARH7_HRM_HEART_RATE_SERVICE_UUID = "180D"

let POLARH7_HRM_MEASUREMENT_CHARACTERISTIC_UUID = "2A37"
let POLARH7_HRM_BODY_LOCATION_CHARACTERISTIC_UUID = "2A39"
let POLARH7_HRM_MANUFACTURER_NAME_CHARACTERISTIC_UUID = "2A29"